# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add two integers
#' 'add_integers_cpp' adds two integers
#' @param a int first integer
#' @param b int second integer
#' @return c int sum of a and b
#'
add_integers_cpp <- function(a, b) {
    .Call(`_QuantTools_add_integers_cpp`, a, b)
}

